### ISSUE TITLE
Something

### ISSUE THREAD

**Issue by LousyLeonard** [jsjlewis96/ai_project#15]

**Comment by JoshYoungman** [comment]
2q + 2q = ?

**Comment by LousyLeonard** [comment]
![image](https://cloud.githubusercontent.com/assets/22559496/19602474/46cd42ca-97a5-11e6-94ce-c6cef14371c2.png)

**Comment by TommyHamblin** [comment]
![image](https://cloud.githubusercontent.com/assets/22937075/19602609/bc987a88-97a5-11e6-9511-23ee2a9d4136.png)

**Comment by LousyLeonard** [comment]
Jake's given up on Paige doing something! :O

**Comment by TommyHamblin** [comment]
Nice mugshot Laz!! Totally flatters you ;)
