### ISSUE TITLE
API Key persistent storage

### ISSUE THREAD

**Issue by DomHoney** [jsjlewis96/ai_project#16]
The form of persistent storage needs to be decided and implemented:
- CSV
- XML 
- JSON
- SQL Database 

The key manager will need to access this storage to be used during runtime.

**Comment by Mattihew** [comment]
My pick would be for CSV as the data is not hierarchical. this allows easy editing of the file directly as well.

**Comment by DomHoney** [comment]
Pull request #25 opened by Matt

**Comment by DomHoney** [comment]
Changes merged into master

**Comment by DomHoney** [comment]
Pull request #28 merged
