### ISSUE TITLE
Create API key storage class(es)

### ISSUE THREAD

**Issue by Mattihew** [jsjlewis96/ai_project#9]
started adding this on branch [Issue #9](/jsjlewis96/ai_project/tree/Issue%239)

**Comment by Mattihew** [comment]
started adding this on branch [Issue #9](/jsjlewis96/ai_project/tree/Issue%239)

**Comment by Mattihew** [comment]
Yeah. issue is still not finished yet.

**Comment by DomHoney** [comment]
Using the title of issue as a basis for closing issue.

All TODOs will be created as new issues, and assigned to the [API Key handling project](https://github.com/jsjlewis96/ai_project/projects/1)
